namespace SpriteKind {
    export const p2 = SpriteKind.create()
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (derection == 0) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . 5 5 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, mySprite, 200, 0)
    } else {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            5 5 . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, mySprite, -200, 0)
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (jump_count < 1) {
        mySprite.vy = -110
        jump_count = 1
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    derection = 1
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.over(false, effects.dissolve)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    derection = 0
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.p2, function (sprite, otherSprite) {
    statusbar.value += -1
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.saplingOak, function (sprite, location) {
    game.over(true)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.disintegrate, 500)
    sprite.destroy()
    list.removeAt(list.indexOf(otherSprite))
})
let projectile_2: Sprite = null
let jump_count = 0
let projectile: Sprite = null
let statusbar: StatusBarSprite = null
let list: Sprite[] = []
let derection = 0
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................................
    ........................................
    ..................cccccc................
    .................cff1fffc...............
    ................cfff111ffc..............
    ...............cff1111111c..............
    ...............cfff1ff11fc..............
    ...............cfff111111c..............
    ...............cfff111111c..............
    ...............cffff11ff1c..............
    ................cfff1f11fc..............
    ..............ccccffff1fc...............
    .............cfffffffffffc..............
    ............cffffffddddfffc.............
    ............c822ffddddddfffc............
    ............c222cffffbbbbbfc............
    ............cfffcfffbfffffbc........b...
    ............cfbbbbbbbbbbbbbbbbbbbbbbbff.
    ............cfbbbbbbbbbbbbbbbbbbbbbbbf..
    ............cfbbbbffbbffbbbbbbbbbb......
    ............cfbbbbfbbfffbbbc............
    .............cbbfffbfffffbb.............
    ..............cffffffffffbb.............
    ..............cdddddddddddc.............
    ..............cddffdddffddc.............
    ..............cfffffffffffc.............
    ..............cfffffffffffc.............
    ..............cfffffffffffc.............
    ..............cffffffffffcc.............
    ..............cffddfffddfc..............
    ..............cffddfcfddfc..............
    ..............cffddfcfddfc..............
    ..............cfffffcfffcc..............
    ..............cfffffcfffffc.............
    ..............cfffffffffffc.............
    ..............ccfffffffffcc.............
    ...............ccccccccccc..............
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 0)
derection = 0
mySprite.setPosition(5, 420)
scene.cameraFollowSprite(mySprite)
mySprite.ay += 200
scene.setBackgroundColor(9)
let mySprite2 = sprites.create(img`
    ........................................
    ................ccccccc.................
    ...............cfffffffc................
    ..............cfffffffffc...............
    ..............cfffffffffc...............
    ..............cdddddddffc...............
    ..............cdf1df1dffc...............
    ..............cdddddddffc...............
    ..............cfffffffffc...............
    ..............cfffffffffc...............
    ..............cffffffffc................
    ...............ccccccccccc..............
    ..............cfffffffffffc.............
    .............cfffeeeeffffffc............
    ............cfffeeeeeeff111c............
    ............cfbbfffffffc888c............
    ...b........cfbbbffffffc222c............
    .ffbbbbbbbbbbbbbbbbbbbbbbbfc............
    ..fbbbbbbbbbbbbbbbbbbbbbbbfc............
    ......bbbbbbbbbbffbbffbbbbfc............
    .............bbbfffbbfbbbbfc............
    .............bbfffffbfffbbc.............
    .............bbffffffffffc..............
    .............ceeceeeecceec..............
    .............ceeceeeecceec..............
    .............cfffffffffffc..............
    .............cfffffffffffc..............
    .............cfffffffffffc..............
    .............ccffffffffffc..............
    ..............cfeefffeeffc..............
    ..............cfeefcfeeffc..............
    ..............cfeefcfeeffc..............
    ..............ccfffcfffffc..............
    .............cfffffcfffffc..............
    .............cfffffffffffc..............
    .............ccfffffffffcc..............
    ..............ccccccccccc...............
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Enemy)
let mysprite_3 = sprites.create(img`
    ........................................
    ................ccccccc.................
    ...............cfffffffc................
    ..............cfffffffffc...............
    ..............cfffffffffc...............
    ..............cdddddddffc...............
    ..............cdf1df1dffc...............
    ..............cdddddddffc...............
    ..............cfddddddffc...............
    ..............cffffffffff...............
    ..............cffffffffc................
    ...............ccccccccccc..............
    ..............cfffffffffffc.............
    .............cfffeeeeffffffc............
    ............cfffeeeeeeff111c............
    ............cffffbfffffc888c............
    ............cffffbbffffc222c............
    .......ffbbbbbbbbbbbbbbbbbfc............
    ..........bbbbbbbbbbbbbbbbfc............
    .............cbbffbbffbbbbfc............
    .............cbbfffbbffffbfc............
    .............cbfffffbffffbc.............
    .............cbffffffffffc..............
    .............ceeceeeecceec..............
    .............ceeceeeecceec..............
    .............cfffffffffffc..............
    .............cfffffffffffc..............
    .............cfffffffffffc..............
    .............ccffffffffffc..............
    ..............cfeefffeeffc..............
    ..............cfeefcfeeffc..............
    ..............cfeefcfeeffc..............
    ..............ccfffcfffffc..............
    .............cfffffcfffffc..............
    .............cfffffffffffc..............
    .............ccfffffffffcc..............
    ..............ccccccccccc...............
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Enemy)
let my_sprite_4 = sprites.create(img`
    ........................................
    ................ccccccc.................
    ...............cfffffffc................
    ..............cfffffffffc...............
    ..............cfffffffffc...............
    ..............cdddddddffc...............
    ..............cdf1df1dffc...............
    ..............cdddddddffc...............
    ..............cfddddddffc...............
    ..............cffffffffff...............
    ..............cffffffffc................
    ...............ccccccccccc..............
    ..............cfffffffffffc.............
    .............cfffeeeeffffffc............
    ............cfffeeeeeeff111c............
    ............cfbbbbbbbbfc888c............
    .b..........cffffbbfbffc222c............
    .bbbbbbbbbbbbbbbbbbbbbbbbbbc............
    ...bbbbbbbbbbbbbbbbbbbbbbbbc............
    ......b...bbbbbbffbbffbbbbbc............
    ......b......bbbfffbbffffbbc............
    .............bbfffffbffffbc.............
    .............bbffffffffffc..............
    .............ceeceeeecceec..............
    .............ceeceeeecceec..............
    .............cfffffffffffc..............
    .............cfffffffffffc..............
    .............cfffffffffffc..............
    .............ccffffffffffc..............
    ..............cfeefffeeffc..............
    ..............cfeefcfeeffc..............
    ..............cfeefcfeeffc..............
    ..............ccfffcfffffc..............
    .............cfffffcfffffc..............
    .............cfffffffffffc..............
    .............ccfffffffffcc..............
    ..............ccccccccccc...............
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Enemy)
mySprite2.setPosition(50, 430)
mysprite_3.setPosition(200, 430)
my_sprite_4.setPosition(400, 430)
mySprite2.ay += 200
mysprite_3.ay += 200
mySprite.setStayInScreen(true)
list = [mySprite2, mysprite_3, my_sprite_4]
tiles.setTilemap(tilemap`level1`)
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.attachToSprite(mySprite)
statusbar.value = 100
game.onUpdateInterval(2000, function () {
    for (let value of list) {
        projectile_2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . 5 5 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, value, -50, 0)
        projectile_2.setKind(SpriteKind.p2)
    }
})
forever(function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        jump_count = 0
    }
})
