namespace SpriteKind {
    export const p2 = SpriteKind.create()
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (derection == 0) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 4 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, mySprite, 100, 0)
    } else {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            4 . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, mySprite, -100, 0)
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (jump_count < 1) {
        mySprite.vy = -100
        jump_count = 1
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    derection = 1
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    derection = 0
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.p2, function (sprite, otherSprite) {
	
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.disintegrate, 500)
})
let projectile_2: Sprite = null
let jump_count = 0
let projectile: Sprite = null
let derection = 0
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................................
    ........................................
    ..................cccccc................
    .................cff1fffc...............
    ................cfff111ffc..............
    ...............cff1111111c..............
    ...............cfff1ff11fc..............
    ...............cfff111111c..............
    ...............cfff111111c..............
    ...............cffff11ff1c..............
    ................cfff1f11fc..............
    ..............ccccffff1fc...............
    .............cfffffffffffc..............
    ............cffffffddddfffc.............
    ............c822ffddddddfffc............
    ............c222cffffbbbbbfc............
    ............cfffcfffbfffffbc........b...
    ............cfbbbbbbbbbbbbbbbbbbbbbbbff.
    ............cfbbbbbbbbbbbbbbbbbbbbbbbf..
    ............cfbbbbffbbffbbbcbbbbbbbb....
    ............cfbbbbfbbfffbbbc............
    .............cbbfffbfffffbb.............
    ..............cffffffffffbb.............
    ..............cdddddddddddc.............
    ..............cddffdddffddc.............
    ..............cfffffffffffc.............
    ..............cfffffffffffc.............
    ..............cfffffffffffc.............
    ..............cffffffffffcc.............
    ..............cffddfffddfc..............
    ..............cffddfcfddfc..............
    ..............cffddfcfddfc..............
    ..............cfffffcfffcc..............
    ..............cfffffcfffffc.............
    ..............cfffffffffffc.............
    ..............ccfffffffffcc.............
    ...............ccccccccccc..............
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 0)
derection = 0
mySprite.setPosition(5, 420)
scene.cameraFollowSprite(mySprite)
mySprite.ay += 200
scene.setBackgroundColor(9)
let mySprite2 = sprites.create(img`
    ........................................
    .............ffffff.....................
    ............f888888f....................
    ...........f8888dd88f...................
    ...........fddddddd88f..................
    ...........f1dd11dd88f..................
    ...........fdddddd888f..................
    ...........fdddddd888f..................
    ...........fdffdd8888f..................
    ...........f2dd88888f...................
    ............f888888ffff.................
    ...........f888888bdd88f................
    ..........f8888888b88888f...............
    .........f88881888bd8888f...............
    .........f888111888d8288f...............
    .........f88881888288222f...............
    .........f28888888288222f...............
    .........f2888888828f822f...............
    .........f2888888888f888f...............
    .........f8888888dd8f828f...............
    .........f8bb888bb88f828f...............
    .........f8d88888dd8f888f...............
    .........f88b888b888f888f...............
    .........f8888888888f888f...............
    ..........f8d88888d8888f................
    ..........f8d88888ddd88f................
    ...........f888888888ff.................
    ...........f8ddd88dddf..................
    ...........f8d2d88d2df..................
    ............fdbd8fdbd8f.................
    ............f8b88f8b88f.................
    ............f8888f8888f.................
    ............f8888f8888f.................
    ...........f8888888888f.................
    ...........f8888888888f.................
    ............ffffffffff..................
    ........................................
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Enemy)
let mysprite_3 = sprites.create(img`
    ........................................
    .............cccccc.....................
    ............cffffffc....................
    ...........cffff22ffc...................
    ...........c2222222ffc..................
    ...........c1221122ffc..................
    ...........c222222fffc..................
    ...........c222222fffc..................
    ...........c2ff22ffffc..................
    ...........c222fffffc...................
    ............cffffffcccc.................
    ...........cffffffbddffc................
    ..........cffdddffbfffffc...............
    .........cffdd1ddfbdffffc...............
    .........cffd111dffdf2ffc...............
    .........cffdd1ddf2ff222c...............
    .........c2ffdddff2ff222c...............
    .........c2fffffff2fcf22c...............
    .........c2fffffffffcfffc...............
    .........cfffffffddfcf2fc...............
    .........cfbbfffbbffcf2fc...............
    .........cfdfffffddfcfffc...............
    .........cffbfffbfffcfffc...............
    .........cffffffffffcfffc...............
    ..........cfdfffffdffffc................
    ..........cfdfffffdddffc................
    ...........cfffffffffcc.................
    ...........cfdddffdddc..................
    ...........cfd2dffd2dc..................
    ............cdbdfcdbdfc.................
    ............cfbffcfbffc.................
    ............cffffcffffc.................
    ............cffffcffffc.................
    ...........cffffffffffc.................
    ...........cffffffffffc.................
    ............cccccccccc..................
    ........................................
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Enemy)
mySprite2.setPosition(147, 420)
mysprite_3.setPosition(159, 430)
mySprite2.ay += 200
mysprite_3.ay += 200
mySprite.setStayInScreen(true)
info.setLife(3)
tiles.setTilemap(tilemap`level1`)
let statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.attachToSprite(mySprite)
game.onUpdateInterval(750, function () {
    projectile_2 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . 6 6 6 6 
        . . . . . . . . . . . . 6 6 6 6 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite2, -50, 0)
    projectile_2.setKind(SpriteKind.p2)
})
forever(function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        jump_count = 0
    }
})
